### ISSUE TITLE
Why not add a special token for empty arrays?

### ISSUE THREAD

**Issue by renzo-orsini** [madnificent/jsown#10]
This is a feature request, rather than an issue of your excellent software. I need to infer as much as possible the structure (let's say the type) of a (quite large) sets of json documents. The fact that an empty array is parsed as nil (like the json value null) makes it impossible to infer the fact that a component is an array. So, analogously to the parameters *parsed-true-value*, *parsed-false-value*, *parsed-null-value*, I suggest the introduction a new parameter like, for instance, *parsed-empty-array-value* with default value nil. 
If you are too busy or not interested in doing this modification, I will try to clone the project and then issue a pull request, if I can avoid to mess with your code! In this case, do you have some suggestion on how to  perform it? Thanks a lot!

**Comment by madnificent** [comment]
The empty list is the only thing represented by NIL.  If it is not, then we should find a way to tweak it so that *is* the case.  Therefore, you should be able to simply match on NIL to figure out whether you're dealing with an empty list or not.

That being said, I could follow the argument that the empty list is nil and that the other nil-like values are receiving special attention.  Why wouldn't the empty list receive such attention?  I could defend the opinion that the empty list is a lisp primitive, whereas :null, :false, :true are interpretations.  However, not everyone may agree with that so I've added the feature in the last commit on master.  This does not seem to have a negative performance impact.  I have *not* enabled this support in #'with-injective-reader as this may be breaking for other consumers, the necessary code has been commented out.  I would prefer to enable this in #'with-injective-reader in the short term as it certainly feels like an inconsistency to define it, yet not use it.  Do we have a way of finding out who is using #'with-injective-reader and checking whether this is going to be breaking for them or not?

**Comment by madnificent** [comment]
No advice received on contacting consumers received.  Support is currently not enabled by default and will stay like this in foreseeable future.  Closing.
