### ISSUE TITLE
User's preference of *read-default-float-format* ignored in favor of single float

### ISSUE THREAD

**Issue by spyrosoft** [madnificent/jsown#11]
I'm sending JSON to the server with double floats. Double float precision is needed to do what I'm trying to do. No matter what I do, I can't seem to maintain the precision.

**Comment by madnificent** [comment]
Are you discussing the parsing of JSON content, or producing JSON content?  The following an explanation of the current way jsown is working.  Could you point me further in the direction where the problem lies?

- ```jsown:parse``` Parsing, where ```*read-default-float-format``` should arguably be followed, produces a ratio.  This ratio can be coerced into a double-float.  We don't coerce here for speed and precision.  I doubt it should yield problems, but if it does, then the conversion should be done by the user.

- ```jsown:to-json``` In terms of producing JSON content, we print a float using the format directive.  The ```*read-default-float-format*``` should not have any impact here.  I don't know of a variable which specifies how floats should be written.  We print the float using the ```~F``` format directive.  We indeed coerce ratio's into floats when writing in a non-configurable way before printing them.  The downside is that this is not configurable, the upside is that conversion already happens.  The following observations may help clarify this behaviour.

Writing a single-float
```
  cl-user> (jsown:to-json (jsown:new-js ("foo" (coerce 100000000000001/100000000000000 'single-float))))
  "{\"foo\":1.0}"
```

Writing a double-float
```
  cl-user> (jsown:to-json (jsown:new-js ("foo" (coerce 100000000000001/100000000000000 'double-float))))
  "{\"foo\":1.00000000000001}"
```

Writing a ratio
```
  cl-user> (let ((*read-default-float-format* 'single-float))
             (jsown:to-json (jsown:new-js ("foo" 100000000000001/100000000000000))))
  "{\"foo\":1.0}"

  cl-user> (let ((*read-default-float-format* 'double-float))
             (jsown:to-json (jsown:new-js ("foo" 100000000000001/100000000000000))))
  "{\"foo\":1.0}"
```

**Comment by spyrosoft** [comment]
I see. The value needs to be modified from a ratio to a double-float prior to being written out again. Thank you for your help. It's fine the way it is.
