### ISSUE TITLE
{"key":null} -> (key . ) (which is unparseable)

### ISSUE THREAD

**Issue by pebblexe** [madnificent/jsown#14]
apparently jsown:parse can't handle this, as it creates a list that impossible to form/read.

**Comment by madnificent** [comment]
That's strange.  I foresee two main ways in which you want to run this, and both work for me.

The first would be with the default settings.  In this case, you read null and represent it as nil in lisp.  It parses correctly.  Writing the value will write out an empty list, rather than null, as lisp doesn't make a distinction between the two.

```
cl-user> (jsown:parse "{\"key\": null}")
(:obj ("key"))
cl-user> (jsown:to-json (jsown:parse "{\"key\": null}"))
"{\"key\":[]}"
```

Alternatively, you could use the injective reader.  Behaviour is a tad different in this case.  You get :null back as a key, but writing the result back gives the same logical content as the input you supplied in the first place.

```
cl-user> (jsown:with-injective-reader (jsown:parse "{\"key\": null}"))
(:obj ("key" . :null))
cl-user> (jsown:with-injective-reader (jsown:to-json (jsown:parse "{\"key\":null}")))
"{\"key\":null}"
```

I don't see a case where `(key . )` is produced.  It does not seem to be a valid lisp form.  On which common lisp implementation does this occur?
