### ISSUE TITLE
Please export function val-safe

### ISSUE THREAD

**Issue by muyinliu** [madnificent/jsown#17]
`val-safe` is a convenient function. Just like in JavaScript `object['key-not-exists']` returns `undefined`.

**Comment by mateusfccp** [comment]
I agree with this. Or, provide a function to check if the key is on the parsed json, something like `(jsown:has-key "foo" bar)`.

**Comment by madnificent** [comment]
Ow, looks like this long-standing request still carries interest.

There is `jsown:keyp` which might serve your needs and helps you work around the issue of `val-safe` not being exported.

I'm also pro exporting `val-safe` but was slightly worried that it might break packages which import jsown completely and which have this method defined themselves.  Perhaps this argument is fairly mute due to the method's naming and common patterns of importing.  Is there a common way of finding out, or is it a gut-feeling thing?

**Comment by mateusfccp** [comment]
> There is jsown:keyp which might serve your needs and helps you work around the issue of val-safe not being exported.

I couldn't find it anywhere in the README. By the way, is there a full documentation of the exported functions?

> I'm also pro exporting val-safe but was slightly worried that it might break packages which import jsown completely and which have this method defined themselves.

Well, packages which import entire jsown may simply shadow `val-safe` if they need to, it's a one-line change... IMHO, it shouldn't be an impeditive. However, the decision is up to you. Is also not hard for me to use `(jsown::val-safe`, but it would be nice to have it exported.

**Comment by madnificent** [comment]
It's now on master.  There's been a bunch of changes so it makes sense to create a new release in the near future.

Regarding documentation: I don't know what the community standard approach to releasing documentation for Lisp systems currently is.  I was hoping https://www.quicklisp.org/beta/UNOFFICIAL/docs/ would be rendering the documentation for the exported symbols.  We should probably dump the documentation discussion in a separate issue.
